name: Integration Test
on: [push]
jobs:
  build:
    runs-on: docker.io/ellerbrock/alpine-bash-curl-ssl
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tufin SecureCloud vulenrabilities analysis
        uses: Tufin/securecloud-image-analysis-action@init
        with:
          securecloud_account: generic-bank
