name: Test Docker Pull and Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Pull the Docker Image
        run: docker pull ubuntu:trusty-20161101
      - name: Vulenrability Analysis
        uses: Tufin/securecloud-image-analysis-action@master
        with:
          securecloud_account: generic-bank
          securecloud_project: retail
          image: ubuntu
          tag: trusty-20161101     
          cve_details: true
        env:
          TUFIN_API_KEY: ${{ secrets.GENERIC_BANK_RETAIL_ALL_TOKEN }}
          TUFIN_DOCKER_REPO_PASSWORD: ${{ secrets.GENERIC_BANK_RETAIL_AGENT_TOKEN }}
