name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tufin SecureCloud vulenrabilities analysis
        uses: Tufin/securecloud-image-analysis-action@init
        with:
          securecloud_account: generic-bank
