name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build the Docker Image
        run: docker build -t image_to_scan:1 . 
      - name: Tufin SecureCloud Vulenrability Analysis
        uses: Tufin/securecloud-image-analysis-action@scan-details
        env:
          TUFIN_API_KEY: ${{ secrets.GENERIC_BANK_RETAIL_ALL_TOKEN }}
          TUFIN_DOCKER_REPO_PASSWORD: ${{ secrets.GENERIC_BANK_RETAIL_AGENT_TOKEN }}
          TUFIN_DOMAIN: generic-bank
          TUFIN_PROJECT: retail
          IMAGE_NAME: image_to_scan
          IMAGE_TAG: 1
